# Generated by Django 5.0.6 on 2024-05-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_ID', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('training_received', models.CharField(max_length=64)),
                ('form_of_land_access', models.CharField(max_length=64)),
                ('source_of_seed', models.CharField(max_length=64)),
                ('main_channel_of_selling', models.CharField(max_length=64)),
                ('major_transition_method', models.CharField(max_length=64)),
                ('main_outlet', models.CharField(max_length=64)),
                ('distance_to_market_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('major_transport_means', models.CharField(max_length=64)),
                ('transport_cost', models.IntegerField()),
            ],
        ),
    ]
